### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by Faizaan2468** [Jakmannob/civ-V_better-turn-timer#1]
Hey, this is a cool idea. Did you ever get it working?

**Comment by MDeiml** [comment]
Haha, I totally forgot about this. I think it worked, you just need to find `MPTurnPanel.lua` in your game files and replace it with the one in this repository.

But I could be wrong, we never actually used it.

**Comment by Faizaan2468** [comment]
Hahah, just tested with a friend and it does work. Can't believe such a basic feature is not in the game!

**Comment by Jakmannob** [comment]
Nice, thanks for testing! Yes, it even seemed to be almost implemented in the code, maybe they just didn't bother finishing it... :D
